"""empty message

Revision ID: 036ed8195240
Revises: ab60553fb869
Create Date: 2023-11-16 09:26:43.897357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036ed8195240'
down_revision = 'ab60553fb869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('sales_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('product_qty', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('sales_date', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sales_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
