"""empty message

Revision ID: 11589bd00cd2
Revises: 57249d37b3d0
Create Date: 2023-12-30 10:31:20.870109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11589bd00cd2'
down_revision = '57249d37b3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_selling_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_cost_price', sa.Float(), nullable=False))
        batch_op.drop_column('total_cost')
        batch_op.drop_column('total_selling')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_selling', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('total_cost', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('total_cost_price')
        batch_op.drop_column('total_selling_price')

    # ### end Alembic commands ###
