"""empty message

Revision ID: 14f4331fe874
Revises: 927882be5b44
Create Date: 2023-12-18 08:06:40.309769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f4331fe874'
down_revision = '927882be5b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productupdate',
    sa.Column('update_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('product_qty', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('created_datereg', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productupdate')
    # ### end Alembic commands ###
