"""empty message

Revision ID: 163c17dd1c65
Revises: 4f32489f368d
Create Date: 2024-01-08 18:25:46.712690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163c17dd1c65'
down_revision = '4f32489f368d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
