"""empty message

Revision ID: 306a22aee28a
Revises: da1e337e2924
Create Date: 2023-11-21 10:26:17.440117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306a22aee28a'
down_revision = 'da1e337e2924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.drop_column('product_limit')

    # ### end Alembic commands ###
