"""empty message

Revision ID: 4119e068a246
Revises: 6e4ddbcad945
Create Date: 2024-01-13 15:40:16.438783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4119e068a246'
down_revision = '6e4ddbcad945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('store_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_name', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
