"""empty message

Revision ID: 4f32489f368d
Revises: d57bb3ac80e6
Create Date: 2024-01-08 17:30:05.042878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f32489f368d'
down_revision = 'd57bb3ac80e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
