"""empty message

Revision ID: 57249d37b3d0
Revises: e445c9c469a3
Create Date: 2023-12-30 10:15:11.520714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57249d37b3d0'
down_revision = 'e445c9c469a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_selling', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_column('total_cost')
        batch_op.drop_column('total_selling')

    # ### end Alembic commands ###
