"""empty message

Revision ID: 6a13eac4bea8
Revises: af0a80f65e19
Create Date: 2023-12-29 13:27:21.668731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a13eac4bea8'
down_revision = 'af0a80f65e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_sold', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('qty_sold')

    # ### end Alembic commands ###
