"""empty message

Revision ID: 8d27951ca681
Revises: 163c17dd1c65
Create Date: 2024-01-08 19:42:43.165422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d27951ca681'
down_revision = '163c17dd1c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', mysql.FLOAT(), nullable=False))

    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
