"""empty message

Revision ID: 927882be5b44
Revises: 306a22aee28a
Create Date: 2023-11-22 10:18:00.688502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927882be5b44'
down_revision = '306a22aee28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_qty', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.drop_column('total_qty')

    # ### end Alembic commands ###
