"""empty message

Revision ID: 9851b7337c9e
Revises: b50aa7e1cc0e
Create Date: 2023-12-30 12:13:00.587678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9851b7337c9e'
down_revision = 'b50aa7e1cc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('total_productqty')

    with op.batch_alter_table('warehouseupdate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_productqty', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouseupdate', schema=None) as batch_op:
        batch_op.drop_column('total_productqty')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_productqty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
