"""empty message

Revision ID: ab60553fb869
Revises: a7ed5b4c6f0a
Create Date: 2023-11-15 20:53:01.856119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab60553fb869'
down_revision = 'a7ed5b4c6f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_column('product_limit')

    # ### end Alembic commands ###
