"""empty message

Revision ID: da1e337e2924
Revises: e23f95804f90
Create Date: 2023-11-20 22:32:21.458964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da1e337e2924'
down_revision = 'e23f95804f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.drop_column('product_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
