"""empty message

Revision ID: e23f95804f90
Revises: 036ed8195240
Create Date: 2023-11-20 21:38:46.097925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23f95804f90'
down_revision = '036ed8195240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispensory', schema=None) as batch_op:
        batch_op.drop_column('product_limit')

    # ### end Alembic commands ###
