"""empty message

Revision ID: f07f50590b31
Revises: 14f4331fe874
Create Date: 2023-12-18 08:10:46.566945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07f50590b31'
down_revision = '14f4331fe874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouseupdate',
    sa.Column('update_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('product_qty', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('created_datereg', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouseupdate')
    # ### end Alembic commands ###
